# -*- coding: utf-8 -*-
"""欢迎使用 Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# 1. 讀取輸入字串
input_data = input()

# 2. 將字串以空格分割成列表
scores_list = input_data.split()

# 3. 初始化計數器
fail_count = 0

# 4. 遍歷列表，判斷分數是否小於 60
for score_str in scores_list:
    # 將字串轉換為整數進行比較
    score = int(score_str)
    if score < 60:
        fail_count += 1

# 5. 輸出結果
print(fail_count)